"""empty message

Revision ID: 955dbfff2ac6
Revises: b83388eecfe8
Create Date: 2024-01-12 20:43:41.080759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955dbfff2ac6'
down_revision = 'b83388eecfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
